### ISSUE TITLE
Show navigation drawer below top nav bar

### ISSUE THREAD

**Issue by manastalukdar** [manastalukdar/manastalukdar.github.io#30]
```javascript
 :clipped="true"
 :mobile-break-point=0
```

References:
- https://github.com/vuetifyjs/vuetify/issues/4911

**Comment by smartops-main** [comment]
I've tried this while testing/learning via the Inspire layout demo for Vuetify.  I have the following settings and I also see the drawer not clipping.  Here's the snippet:

    <div id="app">
        <v-app id="inspire">
            <v-navigation-drawer v-model="drawer"
                                 :clipped="true"
                                 mobile-break-point=0
                                 hide-overlay="true"
                                 disable-resize-watcher="true"
                                 app>
...

My goal is to always have a clipped menu/drawer even on mobile, regardless of app/browser window.  What am I missing?

**Comment by AlexanderZnaydyuk** [comment]
@smartops-main 

In order to achieve that You need to set up both ```v-navigation-drawer``` and ```v-app-bar``` properly.  

```<v-navigation-drawer clipped app>```
+
```<v-app-bar clipped-left app>```
